import type { Plugin, ResolvedId } from "rolldown";

import { randomUUID } from "node:crypto";
import { Filter } from "./utils/filter.js";

export default function awaitEntrypointsPlugin(options: {
	filter: Filter;
	/**
	 * Prefix used for internal variables generated by the plugin.
	 * Change this if it conflicts with variable names in your code.
	 */
	generatedVariablePrefix: string;
}) {
	const generatedVariablePrefix = options.generatedVariablePrefix;

	const proxyPrefix = `\0${generatedVariablePrefix}AwaitEntry:`;
	const awaitedEntriesMap = new Map<string, ResolvedId>();

	return {
		name: "rolldown-plugin-concurrent-tla-plugin-await-entrypoints",
		// @ts-expect-error vite specific properties
		// vite serves modules as ES modules during dev and thus TLA gets handled natively
		apply: "build" as const,

		resolveId: {
			order: "pre",
			async handler(source, importer, extraOptions) {
				if (importer?.startsWith(proxyPrefix)) {
					const key = importer.slice(proxyPrefix.length);
					const resolved = awaitedEntriesMap.get(key);
					if (!resolved) {
						throw new Error(
							"Name collision in concurrent-tla plugin, please change the generatedVariablePrefix option",
						);
					}
					return resolved;
				}

				if (!extraOptions.isEntry && extraOptions.kind !== "dynamic-import") {
					return;
				}

				const resolved = await this.resolve(source, importer, extraOptions);

				// TODO skip "\0" modules?
				if (resolved == null || !options.filter.includes(resolved.id)) return;

				const key = randomUUID();
				awaitedEntriesMap.set(key, resolved);

				return `${proxyPrefix}${key}`;
			},
		},
		load: {
			order: "pre",
			async handler(id) {
				if (id.startsWith(proxyPrefix)) {
					const resolved = awaitedEntriesMap.get(id.slice(proxyPrefix.length));
					if (!resolved) {
						throw new Error(
							"Name collision in concurrent-tla plugin, please change the generatedVariablePrefix option",
						);
					}
					const module = await this.load(resolved);

					if (module.meta[generatedVariablePrefix + "_async"]) {
						return `import { ${generatedVariablePrefix}_access } from "${resolved.id}";
await new Promise(${generatedVariablePrefix}_access);
export * from "${resolved.id}";
`;
					}
					// note that the source here is actually irrelevant
					return `export * from "${resolved.id}";
`;
				}
			},
		},
	} satisfies Plugin;
}
