import type { Plugin } from "rolldown";

import awaitEntrypointsPlugin from "./awaitEntriesPlugin.js";
import registerModulePlugin from "./registerModulePlugin.js";
import transformPlugin from "./transformPlugin.js";

export default function concurrentTopLevelAwait(
	options: {
		// TODO support filter function
		/**
		 * Prefix used for internal variables generated by the plugin.
		 * Change this if it conflicts with variable names in your code.
		 * @default "__tla"
		 */
		generatedVariablePrefix?: string;
	} = {},
) {
	const generatedVariablePrefix = options.generatedVariablePrefix ?? "__tla";
	const enrichedOptions = {
		...options,
		generatedVariablePrefix,
		registerModuleSource: `\0${generatedVariablePrefix}Register`,
	};

	return [
		awaitEntrypointsPlugin(enrichedOptions),
		registerModulePlugin(enrichedOptions),
		transformPlugin(enrichedOptions),
	] satisfies Plugin[] as any[]; // TODO
}
