import type { Plugin } from "rolldown";

import awaitEntrypointsPlugin from "./awaitEntriesPlugin.js";
import registerModulePlugin from "./registerModulePlugin.js";
import transformPlugin from "./transformPlugin.js";

function matchesPattern(id: string, pattern: RegExp | RegExp[]) {
	if (Array.isArray(pattern)) {
		return pattern.some((p) => p.test(id));
	}
	return pattern.test(id);
}

export default function concurrentTopLevelAwait(
	options: {
		// We do not support string patterns because their semantics
		// may change in the future
		include?: RegExp | RegExp[];
		exclude?: RegExp | RegExp[];
		/**
		 * Prefix used for internal variables generated by the plugin.
		 * Change this if it conflicts with variable names in your code.
		 * @default "__tla"
		 */
		generatedVariablePrefix?: string;
	} = {},
) {
	const include = options.include;
	const exclude = options.exclude ?? /\/node_modules\//;
	const generatedVariablePrefix = options.generatedVariablePrefix ?? "__tla";
	const enrichedOptions = {
		...options,
		generatedVariablePrefix,
		registerModuleSource: `\0${generatedVariablePrefix}Register`,
		filter: {
			include,
			exclude,
		},
		filterFn(id: string) {
			if (exclude && matchesPattern(id, exclude)) {
				return false;
			}
			if (include) {
				return matchesPattern(id, include);
			}
			return true;
		},
	};

	return [
		awaitEntrypointsPlugin(enrichedOptions),
		registerModulePlugin(enrichedOptions),
		transformPlugin(enrichedOptions),
	] satisfies Plugin[] as any[]; // TODO
}
