import type { Plugin } from "rolldown";

import { createFilter } from "./utils/filter.js";
import awaitEntrypointsPlugin from "./awaitEntriesPlugin.js";
import registerModulePlugin from "./registerModulePlugin.js";
import transformPlugin from "./transformPlugin.js";

export default function concurrentTopLevelAwait(
	options: {
		// We do not support string patterns because their semantics
		// may change in the future
		include?: RegExp | RegExp[];
		exclude?: RegExp | RegExp[];
		/**
		 * Prefix used for internal variables generated by the plugin.
		 * Change this if it conflicts with variable names in your code.
		 * @default "__tla"
		 */
		generatedVariablePrefix?: string;
	} = {},
) {
	const generatedVariablePrefix = options.generatedVariablePrefix ?? "__tla";
	const enrichedOptions = {
		...options,
		generatedVariablePrefix,
		registerModuleSource: `\0${generatedVariablePrefix}Register`,
		filter: createFilter(
			options.include,
			// TODO .htm and query parameters?
			options.exclude ?? [/\/node_modules\//, /\.html$/],
		),
	};

	return [
		awaitEntrypointsPlugin(enrichedOptions),
		registerModulePlugin(enrichedOptions),
		transformPlugin(enrichedOptions),
	] satisfies Plugin[] as any[]; // TODO
}
