import type { Plugin } from "rolldown";

// Kudos to evanw for figuring out the registry strategy in https://github.com/evanw/tla-fuzzer
const tlaModule = `export default function register(fn, evaluate_accesses) {
    let state = "ready";
    let whenDones = [];
    let whenErrors = [];
    let remaining = 1;
    let error = undefined;
    // evaluate eagerly
    evaluate();

    return evaluate;

    function evaluate(whenDone, onError) {
        if (state === "done") {
            if (whenDone)
                whenDone();
            return;
        }
        if (state === "failed") {
            if (onError)
                onError(error);
            return;
        }
        if (whenDone)
            whenDones.push(whenDone);
        if (onError)
            whenErrors.push(onError);
        if (state === "busy") {
            return;
        }
        state = "busy";
        let moduleDone = () => {
            state = "done";
            for (let x of whenDones)
                x();
        };
        let moduleError = (err) => {
            state = "failed";
            error = err;
            for (let x of whenErrors)
                x(err);
        };
        let importDone = () => {
            if (state !== "busy")
                return;
            if (--remaining !== 0)
                return;
            try {
                let result = fn();
                if (result) {
                    result
                        .then(moduleDone)
                        .catch(moduleError);
                }
                else {
                    moduleDone();
                }
            }
            catch (err) {
                moduleError(err);
            }
        };
        for (const access of evaluate_accesses) {
            let evaluate;
            try {
                // Environment-dependent behavior:
                // - throws on cyclic dependencies in V8
                // - returns undefined in some environments (e.g., vitest)
                evaluate = access();
                if (evaluate == null)
                    continue;
            }
            catch (_a) {
                continue;
            }
            remaining++;
            evaluate(importDone, moduleError);
        }
        importDone();
    }
}
`;

export default function registerModulePlugin(options: {
	// TODO support filter function
	registerModuleSource: string;
	/**
	 * Prefix used for internal variables generated by the plugin.
	 * Change this if it conflicts with variable names in your code.
	 */
	generatedVariablePrefix: string;
}) {
	const generatedVariablePrefix = options.generatedVariablePrefix;
	const registerModuleSource = options.registerModuleSource;

	return {
		name: "rolldown-plugin-concurrent-tla-plugin-register-module",
		// @ts-expect-error vite specific properties
		// vite serves modules as ES modules during dev and thus TLA gets handled natively
		apply: "build" as const,

		resolveId(source) {
			if (source === registerModuleSource) {
				return registerModuleSource;
			}
		},
		load(id) {
			if (id === registerModuleSource) {
				return tlaModule;
			}
		},
	} satisfies Plugin;
}
