// @ts-nocheck

import type { ImportDeclaration } from "estree";
import {
	RolldownMagicString,
	type Plugin,
	type TransformPluginContext,
} from "rolldown";
import { transform as transfromTypescript } from "rolldown/utils";

import hasTopLevelAwait from "../../shared/src/hasTopLevelAwait.js";
import { AsyncModuleTracker } from "../../shared/src/AsyncModuleTracker.js";
import transform from "../../shared/src/transform.js";

// TODO correct values?
const supportedModuleTypes = new Set(["js", "jsx", "ts", "tsx"]);

function resolveDeclarationSource(
	context: TransformPluginContext,
	id: string,
	importerAttributes: Record<string, string> = {},
	declaration: ImportDeclaration,
) {
	return context.resolve(declaration.source.value as string, id, {
		attributes: Object.fromEntries(
			declaration.attributes.map((attr) => [
				attr.key.type === "Identifier" ? attr.key.name : attr.key.value,
				attr.value.value,
			]),
		),
		importerAttributes,
		custom: {},
	});
}

export default function transformPlugin(options: {
	// TODO support filter function
	registerModuleSource: string;
	/**
	 * Prefix used for internal variables generated by the plugin.
	 * Change this if it conflicts with variable names in your code.
	 */
	generatedVariablePrefix: string;
}) {
	const generatedVariablePrefix = options.generatedVariablePrefix;

	const asyncTracker = new AsyncModuleTracker<string>();

	return {
		name: "rolldown-plugin-concurrent-tla-plugin-transform",
		// @ts-expect-error vite specific properties
		// vite serves modules as ES modules during dev and thus TLA gets handled natively
		apply: "build" as const,

		transform: {
			async handler(_code, id, transformOptions) {
				// TODO move filter up to hook
				if (id.startsWith(`\0${generatedVariablePrefix}AwaitEntry:`)) {
					return;
				}

				if (!supportedModuleTypes.has(transformOptions?.moduleType)) {
					asyncTracker.setEntryAsync(id, false);
					asyncTracker.setDependencies(id, []); // TODO required?
				}

				// TODO support typescript directly in transform
				// const ast = transformOptions?.ast ?? this.parse(code, {
				// 	// preserveParens // TODO
				// 	// TODO
				// });
				const code = (
					await transfromTypescript(
						id,
						_code,
						// { lang: transformOptions?.moduleType },
					)
				).code;
				const ast = this.parse(code);

				const importDeclarations = ast.body.filter(
					(a) => a.type === "ImportDeclaration",
				);

				const hasAwait = hasTopLevelAwait(ast);
				asyncTracker.setEntryAsync(id, hasAwait);

				if (hasAwait) {
					// we can skip adding dependencies here, as we know that the module is async anyway
					asyncTracker.setDependencies(id, []);
				}

				let imports = (
					await Promise.all(
						importDeclarations.map(async (declaration) => {
							const importId = await resolveDeclarationSource(
								this,
								id,
								transformOptions?.attributes,
								declaration,
							);
							if (!importId /* TODO filter by id */) return null;
							return {
								declaration,
								id: importId.id,
							};
						}),
					)
				).filter(Boolean) as { declaration: ImportDeclaration; id: string }[];

				if (!hasAwait) {
					asyncTracker.setDependencies(
						id,
						imports.map((x) => x.id),
					);
				}

				const asyncImports = (
					await Promise.all(
						imports.map(async ({ declaration, id }) => {
							// don't await load to not run into deadlock
							this.load({ id });
							if (!(await asyncTracker.isAsync(id))) return null;
							return declaration;
						}),
					)
				).filter(Boolean) as ImportDeclaration[];

				const isAsyncModule = asyncImports.length > 0 || hasAwait;
				if (!isAsyncModule) return;

				const { magicString: _magicString } = transformOptions;
				const magicString = new RolldownMagicString(code);

				// we require experimental.nativeMagicString to be enabled because we
				// will use it as soon as we support typescript in transform directly
				if (!_magicString) {
					throw new Error(
						"experimental.nativeMagicString must be enabled in the Rolldown options to use the concurrent-tla plugin",
					);
				}

				transform(
					magicString,
					ast,
					options.registerModuleSource,
					asyncImports,
					hasAwait,
					generatedVariablePrefix,
				);

				return {
					code: magicString,
					// TODO use asyncTracker instead?
					meta: {
						[generatedVariablePrefix + "_async"]: true,
					},
				};
			},
		},
	} satisfies Plugin;
}
