name: Release

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup Node.js 24
        uses: voidzero-dev/setup-vp@v1.17.0
        with:
          node-version: "24"
          cache: false # avoid cache poisoning attacks

      - name: Install Dependencies
        run: vp install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
          version: vp run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
